### PR TITLE
Jump bug near barrier fix

### PR DESCRIPTION
**Pull request by vadim94**

### CODE REVIEW

**Review by ioan994 — COMMENTED** [review]
According to google code style guide we should use spaces as indentation: https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs.

Although I suggest to use 4 spaces instead of 2.

**Comment by vadim94** [comment]
I will change \t symbol on 4 spaces in the whole file.

**Comment by vadim94** [comment]
Also, I propose to submit this fix first and then to create a separate commit for tab-to-space changes. Do you agree?

**Comment by ioan994** [comment]
Sure, sounds good to me

**Pull request merged**
